version: "3"

services:
  playground:
    image: "ghcr.io/parkgang/dev-env/cpp-basic:latest"
    volumes:
      # Docker에서 수행되는 프로젝트는 한개인데 굳이 이름을 구분하는 이유는 `WakaTime` 와 같은 곳에서 프로젝트 이름을 인식하기 위함
      - .:/repo/coding-test
